apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook
  namespace: guestbook
spec:
  host: guestbook.apps.cluster-6cq5t.6cq5t.sandbox1092.opentlc.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: frontend
    weight: 100