apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook
  namespace: guestbook
spec:
  host: guestbook.apps.aws-us-west-2-c4.sandbox499.opentlc.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: frontend
    weight: 100